### ISSUE TITLE
Still the issue prist Catalina will ne be supported this policy 

### ISSUE THREAD

**Issue by mani2care** [TravellingTechGuy/manageSecureTokens#3]
Still the issue prist Catalina will ne be supported this policy

**Comment by TravellingTechGuy** [comment]
Not sure what you mean here. I run this in Catalina

**Comment by mani2care** [comment]
I'm getting this error on my MAC.


Thanks & Regards,

R. Manikandan.
E-mail: mani2care@gmail.com
Linkedin: www.linkedin.com/in/mani2care
Contact: 9902103878.

**Comment by mani2care** [comment]
Can find the error  
#[
<img width="498" alt="secure token issue " src="https://user-images.githubusercontent.com/52978899/94922626-3430ea00-04d8-11eb-965c-3d1b2d68e6b4.png">
](url)

**Comment by TravellingTechGuy** [comment]
Just replicated the issue by running the following manually in terminal

dscl /Local/Default authonly $userName $userPass

Replace $userName and $userPass with actual username and password => works fine for me.

Tried again providing wrong password and I do get the error.

Authentication for node /Local/Default failed. (-14090, eDSAuthFailed)
<dscl_cmd> DS Error: -14090 (eDSAuthFailed)

Can you run that command manually and provide username and password in Terminal and see what you get?

**Comment by mani2care** [comment]
I have tried the with the current user name and password but no luck still
the same getting the same error.
attached image for the reference.

Thanks & Regards,

R. Manikandan.
E-mail: mani2care@gmail.com

**Comment by TravellingTechGuy** [comment]
If the command I gave you does not work in Terminal and throws the same error, then it's not the script but a problem with the account or the DS node. Closing this issue.
